server:
  port: 8083

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowedCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
          filters:
            - RewritePath=/department/(?<path>.*), /$\{path}
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/